# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Benjamin Durham
title: Founder Of Tier III Technologies
email: admin@bencey.co.nz
website: www.bencey.co.nz

# Social links
twitter_username: bencey4
github_username:  bencey
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: benjamin_durham_westhead
linkedin_username: benjamin-durham-324275178
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Benjamin and I am an IT freelancer and the founder of Tier III Technologies, I have experience in a wide variety of fields such as Web Development, Software Development, Customer Service, Systems Administration and more. I am currently looking for work and you can contact me [Here](mailto:admin@bencey.co.nz)

  I am most skilled in: <mark>Web Development</mark> and <mark>Systems Administration</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Certifications / Qualifications

# Education Section
# educaton_title: Education

# More Section
more_title: Further Information
more_content: | # this will include new lines to allow paragraphs
  Here are some of my interests and hobbies:
   - Gaming
   - Cyber Security
   - Systems Administration
   - Community Management
   - Content Creation (Blogging, Streaming)
   - Customer Support (Tech Support)
   - Integrations Between Technologies
   - System APIs
   - Development (Website, Software, Hardware)
  
  Here are some of the things I have experience/Knowledge in:
   - Zendesk
   - WHMCS
   - JavaScript
   - Python
   - HTML, CSS, PHP
   - Linux, Windows and Apple Systems
   - Nodejs
   - Git

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
